"""Add capital_stock and capital_updated_at to stocks table

Revision ID: 30fff3dcd91b
Revises: 001
Create Date: 2025-09-23 09:21:12.558213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "30fff3dcd91b"
down_revision: Union[str, None] = "001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "stocks",
        sa.Column(
            "capital_stock",
            sa.BigInteger(),
            nullable=True,
            comment="實收資本額（股本）單位：元",
        ),
    )
    op.add_column(
        "stocks",
        sa.Column(
            "capital_updated_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="股本資料更新時間",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("stocks", "capital_updated_at")
    op.drop_column("stocks", "capital_stock")
    # ### end Alembic commands ###
